version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-fix-service
    ports:
      - "8080:8080"
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/schedulefix
    #   SPRING_DATASOURCE_USERNAME: postgres
    #   SPRING_DATASOURCE_PASSWORD: postgres
    # depends_on:
    #   - db

  # db:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_DB: schedulefix
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data: