version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tokmann/schedulefixservice-app:2.0
    container_name: schedule-fix-service
    ports:
      - "8080:8080"
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/schedule_fix_db
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: tokman
    depends_on:
       - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s

  db:
     image: postgres:latest
     container_name: postgres-db
     environment:
       POSTGRES_DB: schedule_fix_db
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: tokman
     ports:
       - "5432:5432"
     volumes:
       - postgres-data:/var/lib/postgresql/data

volumes:
   postgres-data: